/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: satkuri (https://sketchfab.com/satkuri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-sketchbook-6-education-icon-270fddebed144f4fbf5a1ba73c3812d3
Title: 3D Sketchbook 6 - Education Icon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Degree =(props) =>{
  const { nodes, materials } = useGLTF('/models/education.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.297, 0]} rotation={[0, 0.554, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Book2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Pages}
        />
      </group>
      <group position={[0, 1.067, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.Rope}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.Bead}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Book1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Pages}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.material}
        position={[0, 1.049, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/education.glb');
export default Degree;
